const offers = [
  {
    id: 'deposit',
    link: 'deposit',
    category: 'Вклады',
    categoryUrl: './img/services/icons/deposits-icon.svg',
    title: 'Вклады Лига Банка – это выгодная инвестиция в свое будущее',
    options: [
      { id: 'd1', text: 'Проценты по вкладам до 7%' },
      { id: 'd2', text: 'Разнообразные условия' },
      { id: 'd3', text: 'Возможность ежемесячной капитализации или вывод процентов на банковскую карту' },
    ],
    imageDescription: 'Копилка в виде поросёнка',
    urlMobile: './img/services/deposits-mobile.jpg',
    urlTablet: './img/services/deposits-tablet.jpg',
    urlDesktop: './img/services/deposits-desktop.jpg',
  },
  {
    id: 'credit',
    category: 'Кредиты',
    categoryUrl: './img/services/icons/credits-icon.svg',
    title: 'Лига Банк выдает кредиты под любые цели',
    options: [
      { id: 'c1', text: 'Ипотечный кредит' },
      { id: 'c2', text: 'Автокредит' },
      { id: 'c3', text: 'Потребительский кредит' },
    ],
    info: {
      desc: 'Рассчитайте ежемесячный платеж и ставку по кредиту воспользовавшись нашим ',
      link: 'кредитным калькулятором',
    },
    imageDescription: 'Изображение горки круглых монет с синей машиной на их вершине',
    urlMobile: './img/services/credits-mobile.jpg',
    urlTablet: './img/services/credits-tablet.jpg',
    urlDesktop: './img/services/credits-desktop.jpg',
  },
  {
    id: 'insurance',
    link: 'insurance',
    category: 'Страхование',
    categoryUrl: './img/services/icons/insurance-icon.svg',
    title: 'Лига Страхование — застрахуем все что захотите',
    options: [
      { id: 'in1', text: 'Автомобильное страхование' },
      { id: 'in2', text: 'Страхование жизни и здоровья' },
      { id: 'in3', text: 'Страхование недвижимости' },
    ],
    imageDescription: 'Изображение синего навесного замка с белым сердцем по середине',
    urlMobile: './img/services/insurance-mobile.png',
    urlTablet: './img/services/insurance-tablet.png',
    urlDesktop: './img/services/insurance-desktop.png',
  },
  {
    id: 'online-service',
    link: 'online-service',
    category: 'Онлайн-сервисы',
    categoryUrl: './img/services/icons/online-services-icon.svg',
    title: 'Лига Банк — это огромное количество онлайн-сервисов для вашего удобства',
    options: [
      { id: 'os1', text: 'Мобильный банк, который всегда под рукой' },
      { id: 'os2', text: 'Приложение Лига-проездной позволит вам оплачивать билеты по всему миру' },
    ],
    imageDescription: 'Изображение мобильного телефона с приложением Лига-Банка',
    urlMobile: './img/services/online-services-mobile.png',
    urlTablet: './img/services/online-services-tablet.png',
    urlDesktop: './img/services/online-services-desktop.png',
  },
];

export default offers;
