const offers = [
  {
    id: 'deposit',
    link: 'deposit',
    category: 'Вклады',
    categoryUrl: './img/services/icons/deposits-icon.svg',
    title: 'Вклады Лига Банка – это выгодная инвестиция в свое будущее',
    options: [
      { id: 'd1', text: 'Проценты по вкладам до 7%' },
      { id: 'd2', text: 'Разнообразные условия' },
      { id: 'd3', text: 'Возможность ежемесячной капитализации или вывод процентов на банковскую карту' },
    ],
    imageDescription: 'Копилка в виде поросёнка',
    url: {
      mobile: './img/services/deposits-mobile.jpg',
      mobileWebp: './imgWebp/services/deposits-mobile.webp',
      mobileRetina: './img/services2x/deposits-mobile2x.jpg',
      mobileRetinaWebp: './imgWebp/services2x/deposits-mobile2x.webp',
      tablet: './img/services/deposits-tablet.jpg',
      tabletWebp: './imgWebp/services/deposits-tablet.webp',
      tabletRetina: './img/services2x/deposits-tablet2x.jpg',
      tabletRetinaWebp: './imgWebp/services2x/deposits-tablet2x.webp',
      desktop: './img/services/deposits-desktop.jpg',
      desktopWebp: './imgWebp/services/deposits-desktop.webp',
      desktopRetina: './img/services2x/deposits-desktop2x.jpg',
      desktopRetinaWebp: './imgWebp/services2x/deposits-desktop2x.webp',
    },
  },
  {
    id: 'credit',
    category: 'Кредиты',
    categoryUrl: './img/services/icons/credits-icon.svg',
    title: 'Лига Банк выдает кредиты под любые цели',
    options: [
      { id: 'c1', text: 'Ипотечный кредит' },
      { id: 'c2', text: 'Автокредит' },
      { id: 'c3', text: 'Потребительский кредит' },
    ],
    info: {
      desc: 'Рассчитайте ежемесячный платеж и ставку по кредиту воспользовавшись нашим ',
      link: 'кредитным калькулятором',
    },
    imageDescription: 'Изображение горки круглых монет с синей машиной на их вершине',
    url: {
      mobile: './img/services/credits-mobile.jpg',
      mobileWebp: './imgWebp/services/credits-mobile.webp',
      mobileRetina: './img/services2x/credits-mobile2x.jpg',
      mobileRetinaWebp: './imgWebp/services2x/credits-mobile2x.webp',
      tablet: './img/services/credits-tablet.jpg',
      tabletWebp: './imgWebp/services/credits-tablet.webp',
      tabletRetina: './img/services2x/credits-tablet2x.jpg',
      tabletRetinaWebp: './imgWebp/services2x/credits-tablet2x.webp',
      desktop: './img/services/credits-desktop.jpg',
      desktopWebp: './imgWebp/services/credits-desktop.webp',
      desktopRetina: './img/services2x/credits-desktop2x.jpg',
      desktopRetinaWebp: './imgWebp/services2x/credits-desktop2x.webp',
    },
  },
  {
    id: 'insurance',
    link: 'insurance',
    category: 'Страхование',
    categoryUrl: './img/services/icons/insurance-icon.svg',
    title: 'Лига Страхование — застрахуем все что захотите',
    options: [
      { id: 'in1', text: 'Автомобильное страхование' },
      { id: 'in2', text: 'Страхование жизни и здоровья' },
      { id: 'in3', text: 'Страхование недвижимости' },
    ],
    imageDescription: 'Изображение синего навесного замка с белым сердцем по середине',
    url: {
      mobile: './img/services/insurance-mobile.png',
      mobileWebp: './imgWebp/services/insurance-mobile.webp',
      mobileRetina: './img/services2x/insurance-mobile2x.png',
      mobileRetinaWebp: './imgWebp/services2x/insurance-mobile2x.webp',
      tablet: './img/services/insurance-tablet.png',
      tabletWebp: './imgWebp/services/insurance-tablet.webp',
      tabletRetina: './img/services2x/insurance-tablet2x.png',
      tabletRetinaWebp: './imgWebp/services2x/insurance-tablet2x.webp',
      desktop: './img/services/insurance-desktop.png',
      desktopWebp: './imgWebp/services/insurance-desktop.webp',
      desktopRetina: './img/services2x/insurance-desktop2x.png',
      desktopRetinaWebp: './imgWebp/services2x/insurance-desktop2x.webp',
    },
  },
  {
    id: 'online-service',
    link: 'online-service',
    category: 'Онлайн-сервисы',
    categoryUrl: './img/services/icons/online-services-icon.svg',
    title: 'Лига Банк — это огромное количество онлайн-сервисов для вашего удобства',
    options: [
      { id: 'os1', text: 'Мобильный банк, который всегда под рукой' },
      { id: 'os2', text: 'Приложение Лига-проездной позволит вам оплачивать билеты по всему миру' },
    ],
    imageDescription: 'Изображение мобильного телефона с приложением Лига-Банка',
    url: {
      mobile: './img/services/online-services-mobile.png',
      mobileWebp: './imgWebp/services/online-services-mobile.webp',
      mobileRetina: './img/services2x/online-services-mobile2x.png',
      mobileRetinaWebp: './imgWebp/services2x/online-services-mobile2x.webp',
      tablet: './img/services/online-services-tablet.png',
      tabletWebp: './imgWebp/services/online-services-tablet.webp',
      tabletRetina: './img/services2x/online-services-tablet2x.png',
      tabletRetinaWebp: './imgWebp/services2x/online-services-tablet2x.webp',
      desktop: './img/services/online-services-desktop.png',
      desktopWebp: './imgWebp/services/online-services-desktop.webp',
      desktopRetina: './img/services2x/online-services-desktop2x.png',
      desktopRetinaWebp: './imgWebp/services2x/online-services-desktop2x.webp',
    },
  },
];

export default offers;
