env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
  - 'plugin:jsx-a11y/strict'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - jsx-a11y
rules:
   react/jsx-props-no-spreading: 0
   jsx-a11y/label-has-associated-control: 0
   jsx-a11y/label-has-for: 0

