const slides = [
  {
    id: 'credit',
    description: 'Синяя страница слайдера с изображением банковской карты',
    text: 'Кредиты на любой случай',
    buttonText: 'Рассчитать кредит',
    urlDesktop: './img/slider/main-desktop.jpg',
    urlDesktopWebp: './imgWebp/slider/main-desktop.webp',
    urlDesktopRetina: './img/slider2x/main-desktop2x.jpg',
    urlDesktopRetinaWebp: './imgWebp/slider2x/main-desktop2x.webp',
    urlTablet: './img/slider/main-tablet.jpg',
    urlTabletWebp: './imgWebp/slider/main-tablet.webp',
    urlTabletRetina: './img/slider2x/main-tablet2x.jpg',
    urlTabletRetinaWebp: './imgWebp/slider2x/main-tablet2x.webp',
    urlMobile: './img/slider/main-mobile.jpg',
    urlMobileWebp: './imgWebp/slider/main-mobile.webp',
    urlMobileRetina: './img/slider2x/main-mobile2x.jpg',
    urlMobileRetinaWebp: './imgWebp/slider2x/main-mobile2x.webp',
  },
  {
    id: 'future',
    description: 'Страница слайдера с изображением мужчины в костюме',
    text: 'Ваша уверенность в завтрашнем дне',
    urlDesktop: './img/slider/man-desktop.jpg',
    urlDesktopWebp: './imgWebp/slider/man-desktop.webp',
    urlDesktopRetina: './img/slider2x/man-desktop2x.jpg',
    urlDesktopRetinaWebp: './imgWebp/slider2x/man-desktop2x.webp',
    urlTablet: './img/slider/man-tablet.jpg',
    urlTabletWebp: './imgWebp/slider/man-tablet.webp',
    urlTabletRetina: './img/slider2x/man-tablet2x.jpg',
    urlTabletRetinaWebp: './imgWebp/slider2x/man-tablet2x.webp',
    urlMobile: './img/slider/man-mobile.jpg',
    urlMobileWebp: './imgWebp/slider/man-mobile.webp',
    urlMobileRetina: './img/slider2x/man-mobile2x.jpg',
    urlMobileRetinaWebp: './imgWebp/slider2x/man-mobile2x.webp',
  },
  {
    id: 'branch',
    description: 'Страница слайдера с изображением девушки с карточкой',
    text: 'Всегда рядом',
    buttonText: 'Найти отделение',
    urlDesktop: './img/slider/girl-desktop.jpg',
    urlDesktopWebp: './imgWebp/slider/girl-desktop.webp',
    urlDesktopRetina: './img/slider2x/girl-desktop2x.jpg',
    urlDesktopRetinaWebp: './imgWebp/slider2x/girl-desktop2x.webp',
    urlTablet: './img/slider/girl-tablet.jpg',
    urlTabletWebp: './imgWebp/slider/girl-tablet.webp',
    urlTabletRetina: './img/slider2x/girl-tablet2x.jpg',
    urlTabletRetinaWebp: './imgWebp/slider2x/girl-tablet2x.webp',
    urlMobile: './img/slider/girl-mobile.jpg',
    urlMobileWebp: './imgWebp/slider/girl-mobile.webp',
    urlMobileRetina: './img/slider2x/girl-mobile2x.jpg',
    urlMobileRetinaWebp: './imgWebp/slider2x/girl-mobile2x.webp',
  },
];

export default slides;
