const slides = [
  {
    id: 'credit',
    description: 'Синяя страница слайдера с изображением банковской карты',
    text: 'Кредиты на любой случай',
    buttonText: 'Рассчитать кредит',
    url: {
      desktop: './img/slider/main-desktop.jpg',
      desktopWebp: './imgWebp/slider/main-desktop.webp',
      desktopRetina: './img/slider2x/main-desktop2x.jpg',
      desktopRetinaWebp: './imgWebp/slider2x/main-desktop2x.webp',
      tablet: './img/slider/main-tablet.jpg',
      tabletWebp: './imgWebp/slider/main-tablet.webp',
      tabletRetina: './img/slider2x/main-tablet2x.jpg',
      tabletRetinaWebp: './imgWebp/slider2x/main-tablet2x.webp',
      mobile: './img/slider/main-mobile.jpg',
      mobileWebp: './imgWebp/slider/main-mobile.webp',
      mobileRetina: './img/slider2x/main-mobile2x.jpg',
      mobileRetinaWebp: './imgWebp/slider2x/main-mobile2x.webp',
    },
  },
  {
    id: 'future',
    description: 'Страница слайдера с изображением мужчины в костюме',
    text: 'Ваша уверенность в завтрашнем дне',
    url: {
      desktop: './img/slider/man-desktop.jpg',
      desktopWebp: './imgWebp/slider/man-desktop.webp',
      desktopRetina: './img/slider2x/man-desktop2x.jpg',
      desktopRetinaWebp: './imgWebp/slider2x/man-desktop2x.webp',
      tablet: './img/slider/man-tablet.jpg',
      tabletWebp: './imgWebp/slider/man-tablet.webp',
      tabletRetina: './img/slider2x/man-tablet2x.jpg',
      tabletRetinaWebp: './imgWebp/slider2x/man-tablet2x.webp',
      mobile: './img/slider/man-mobile.jpg',
      mobileWebp: './imgWebp/slider/man-mobile.webp',
      mobileRetina: './img/slider2x/man-mobile2x.jpg',
      mobileRetinaWebp: './imgWebp/slider2x/man-mobile2x.webp',
    },
  },
  {
    id: 'branch',
    description: 'Страница слайдера с изображением девушки с карточкой',
    text: 'Всегда рядом',
    buttonText: 'Найти отделение',
    url: {
      desktop: './img/slider/girl-desktop.jpg',
      desktopWebp: './imgWebp/slider/girl-desktop.webp',
      desktopRetina: './img/slider2x/girl-desktop2x.jpg',
      desktopRetinaWebp: './imgWebp/slider2x/girl-desktop2x.webp',
      tablet: './img/slider/girl-tablet.jpg',
      tabletWebp: './imgWebp/slider/girl-tablet.webp',
      tabletRetina: './img/slider2x/girl-tablet2x.jpg',
      tabletRetinaWebp: './imgWebp/slider2x/girl-tablet2x.webp',
      mobile: './img/slider/girl-mobile.jpg',
      mobileWebp: './imgWebp/slider/girl-mobile.webp',
      mobileRetina: './img/slider2x/girl-mobile2x.jpg',
      mobileRetinaWebp: './imgWebp/slider2x/girl-mobile2x.webp',
    },
  },
];

export default slides;
